### ISSUE TITLE
HowTo get Window in Mono

### ISSUE THREAD

**Issue by Axel-Erfurt** [Baltasarq/GtkUtil#1]
In Mono on Linux,
I set to GUI Application in Options.
get an error:

> Error CS5001: Program `GtkUtil.exe' does not contain a static`Main' method suitable for an entry point (CS5001) (GtkUtil)

I added 

```
public class Program
{
    public static void Main ()
    {
        Application.Run ();
    }
}
```

it starts, but without Window.

**Comment by Baltasarq** [comment]
I'm not sure whether you're sending this e.mail to the right address.
GtkUtil has to do with Gtk#, yes, but it just adds some utility methods.

Gtk# is here:
https://github.com/mono/gtk-sharp

> I set to GUI Application in Options.
> get an error:
> Error CS5001: Program GtkUtil.exe' does not contain a staticMain' method
> suitable for an entry point (CS5001) (GtkUtil)
> 
> I added
> 
> public class Program
> {
>     public static void Main ()
>     {
>         Application.Run ();
>     }
> }
 
Okay. I think you've added the GtkUtil module to your program. You've to start the program in the canonic way, say you have a Window called MainWindow:

```
public class Program
{
    public static void Main ()
    {
        MainWindow win = new MainWindow();

        Application.Init();
        win.showAll();

        Application.Run();
    }
}
```

You have a tutorial for Gtk# using MonoDevelop/XamarinStudio here:
http://www.monodevelop.com/documentation/stetic-gui-designer/

Hope this helps.
-- baltasar
